# Generated by Django 3.2.8 on 2021-11-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_auto_20211110_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='battery',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='memory',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='vin',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
